#' @title deploy_project
#' @description Writes fabric deployment info based on specifications in yaml file.
#' Should always be called from the root project directory.
#' @param  iter_arg Name of argument over which parallel execution job should be bult.
#' @param  deploy_file Path to yaml file specifying arguments and function calls.
#' @import yaml
#' @export


deploy_project <- function(iter_arg = NULL, deploy_conf = "jenkins/deploy.yaml",
                           packrat = TRUE) {

 message("Packaging project for fabric-jenkins deployment..")
 conf <- yaml::yaml.load_file(deploy_conf)
 prep_deploy_files(deploy_conf = deploy_conf)
 build_virtualenv_job(conf = conf)

 for (executor in conf$executables) {

  message(sprintf("Rendering template for job: %s", names(executor)))
  build_single_task_job(entry = executor[[1]], conf = conf,
                        job_name = names(executor))

  build_parallel_run_job(iter_arg = iter_arg, args = executor[[1]]$function_args,
                         conf = conf, job_name = names(executor))

 }

 build_packrat_job(conf = conf)

 if (packrat) {
  deploy_packrat()
 }

 if (!"./packrat" %in% list.dirs(recursive = T)) {
  if (packrat) {
   stop("No packrat directory found for this project!")
  }else{
   warning("No packrat directory found. Be sure to create one before deploying!")
  }
 }

 message("Deployment files successfully created!")
}


#' @title validate_deploy_entry
#' @description Validates the .R function specified by the deployment file.
#' @param job Name of job to be validated.
#' @param file file path to validate.
#' @param args Argument names to check in file

validate_deploy_entry <- function(job, file, args) {

 message(sprintf("Validating function: %s in file: %s", job, file))

 if (!grepl("\\.r$", tolower(file))) {
  stop("File specified in deploy yaml is not an R file!")
 }

 if (!file.exists(file)) {
  stop(sprintf("No File exists at %s for job: %s", file, job))
 }

 code = paste0(readLines(file), collapse = "\n")
 if (!grepl("make_option\\(", code)) {
  stop(sprintf("No optparse arguments found in file %s. Try again.", file))
 }

 for (arg in args) {
  message(sprintf("Checking arg: %s", arg))
  if (!grepl(arg, code)) {
   stop(sprintf("Argument: %s not found in file %s", arg, file))
  }
 }

 message("Validation successful...")
}


#' @title deploy_packrat
#' @description Deploys packrat for you, so that you don't have to.

deploy_packrat <- function() {

 message("Creating packrat lib...")

 if ("package:packrat" %in% search()) {
  packrat::off()
  hacky_thing = TRUE
 }else{
  hacky_thing = FALSE
 }

 if (validate_devtools_install()) {
  message("devtools install valid")
 }else{
  message("invalid devtools installation found.  Installing newer version...")
  install.packages("devtools", repos = "https://cran.rstudio.com")
 }

 if (hacky_thing) {
  packrat::on()
 }

 if (!"packrat" %in% row.names(installed.packages())) {
  message("No local packrat installation found.. attempting to install...")
  install.packages("packrat", repos = "https://cran.rstudio.com")
 }

 packrat::init(restart = FALSE)

 message("Packrat deployment successfull")
}


validate_devtools_install <- function() {

 val = (!"devtools" %in% row.names(installed.packages()) ||
         compareVersion(gsub("\\’|\\‘", "", packageVersion("devtools")),
                        "1.12.0") != (-1))
 return(val)
}


#' @title prep_deploy_files
#' @description Ensures proper directories exist, checks for fabfile conflicts,
#' and moves templates to correct locations.
#' @param deploy_conf locatation of deploy_conf.yaml file.

prep_deploy_files <- function(deploy_conf) {

 if (!file.exists(deploy_conf)) {
  make_deploy_template()
  stop("No deploy yaml file was found for this project.
      One has been created for you at deploy.yaml.
      Fill it out, then retry!")
 }

 dir.create("deploy", showWarnings = FALSE)
 dir.create("jenkins", showWarnings = FALSE)
 writeBin("", "deploy/__init__.py")

 if (file.exists("fabfile.py")) {

  if (!grepl("generated by mmkit",
             paste0(readLines("fabfile.py"), collapse = " "))) {
   stop("Non mmkit fabfile.py found in directory.  Please remove and try again.")
  }

  message("Removing existing fabfile.py")
  file.remove("fabfile.py")

 }

 file.copy(paste0(system.file(package = "mmkit"), "/jenkins/fab_deploy_template.txt"),
           "fabfile.py")

 file.copy(paste0(system.file(package = "mmkit"), "/jenkins/requirements.txt"),
           "requirements.txt")

 message("Deploy files prepared")
}


#' @title generate_xml_config
#' @description Utility to generate xml configs from template.

generate_xml_config <- function(job_type, github_https_address = NULL,
                                email = NULL, args = NULL,
                                job_name, job_code, project_url = NULL) {

 if (job_type == "create_env") {

  message("Reading xml template for create-env job...")
  xml_tmp <- mmkit:::read_text("/jenkins/create_env_template.xml")

  xml_tmp <- str_form(xml_tmp, project_url = project_url,
                      job_name = job_name, job_code = job_code,
                      github_https_address = github_https_address)
  message("Exporting rendered xml template...")

  writeLines(xml_tmp, "jenkins/create_virtual_env.xml")

 }else if (job_type == "task") {

  message("Reading xml template for task execution job...")

  arg_temp <- mmkit:::read_text("/jenkins/jenkins_param_tmp.txt")
  arg_params <- paste0(lapply(args, FUN = function(X) {
   str_form(arg_temp, arg_name = X) }), collapse = "\n")

  xml_tmp <- mmkit:::read_text("/jenkins/jenkins_task_template.xml")
  xml_tmp <- str_form(xml_tmp, job_name = job_name,
                      arguments = arg_params, email = email,
                      job_code = job_code)

  writeLines(xml_tmp, sprintf("jenkins/run_task_%s.xml", job_name))

 }else if (job_type == "build_loop") {

  message("Reading xml template for loop execution job...")

  arg_temp <- mmkit:::read_text("/jenkins/jenkins_param_tmp.txt")
  arg_params <- paste0(lapply(args, FUN = function(X) {
   str_form(arg_temp, arg_name = X) }), collapse = "\n")

  xml_tmp <- mmkit:::read_text("/jenkins/jenkins_parallel_execute_template.xml")
  xml_tmp <- str_form(xml_tmp, job_name = job_name,
                      arguments = arg_params, email = email,
                      job_code = job_code)

  writeLines(xml_tmp, sprintf("jenkins/run_task_%s.xml", job_name))


 }else{

  stop("Job type not configured")

 }

 message("xml template written successfully")
}


#' @title export_jobs_to_jenkins
#' @description Exports the pre-populated xml files in the jenkins directory to
#' the server.
#' @param user Jenkins user email address used to authenticate. Defaults to
#' project user email found in jenkins deploy.yaml file.
#' @param api_token The api token associated with the jenkins user being used.
#' By default, mmkit will look for a system enviroment var called jenkins_api_token.
#' @param project_name Project name - Used as prefix for jobs being created.
#' By default, mmkit will try to read this information from the jenkins/deploy.yaml file.
#' @param host Hostname of the jenkins server where jobs should be created.
#' Defaults to https://corp-bi-jenkins-prod.2u.com.  Don't change this.
#' @import httr
#' @export

export_jobs_to_jenkins <- function(
 user = yaml::yaml.load_file("jenkins/deploy.yaml")$user_email,
 api_token = Sys.getenv("jenkins_api_token"),
 project = yaml::yaml.load_file("jenkins/deploy.yaml")$project_name,
 host = "https://corp-bi-jenkins-prod.2u.com") {

 message("Exporting jobs to jenkins host...")
 files = list.files("jenkins/", full.names = TRUE, pattern = "\\.xml$")

 project = simpleCap(project)

 for (file in files) {

  message(sprintf("Exporting job: %s", file))

  project <- simpleCap(project)
  job = gsub("\\.xml", "", basename(file))
  job_data <- paste0(readLines(file), collapse = "\n")
  jenkins_name <- str_form("createItem?name={{project}}_{{job}}",
                           job = job, project = project)

  post_url <- str_form("{{host}}/{{jenkins_name}}",
                       host = host, jenkins_name = jenkins_name)

  auth = httr::authenticate(user = user, api_token)

  post = httr::POST(url = post_url, content_type = "application/xml",
                    auth, body = upload_file(file))

  httr::stop_for_status(post)

 }

 message("All templates have updated")

}


build_single_task_job <- function(conf, entry, job_name) {

 message("Reading xml template for task execution job...")

 validate_deploy_entry(file = entry$file_location, job = job_name,
                       args = entry$function_args)

 task_args = paste0(lapply(entry$function_args, FUN = function(X) {
  str_form("{{arg}}=${{arg}}", arg = X) }), collapse = ",")

 single_job = str_form(read_text("/jenkins/run_task_jenkins.txt"),
                       project_dir = conf$project_name, job_name = job_name,
                       arguments = task_args)

 arg_temp <- mmkit:::read_text("/jenkins/jenkins_param_tmp.txt")
 arg_params <- paste0(lapply(entry$function_args, FUN = function(X) {
  str_form(arg_temp, arg_name = X) }), collapse = "\n")

 xml_tmp <- mmkit:::read_text("/jenkins/jenkins_task_template.xml")
 xml_tmp <- str_form(xml_tmp, job_name = job_name,
                     arguments = arg_params, email = conf$user_email,
                     job_code = single_job)

 writeLines(xml_tmp, sprintf("jenkins/run_task_%s.xml", job_name))

 message("Appending task call to fabfile...")
 append_task_to_fabfile(entry = entry, conf = conf, job_name = job_name)

 message("Task job build successfully...")

}


#' @title append_task_to_fabfile
#' @description Appends task function definition to fabfile.

append_task_to_fabfile <- function(entry, conf, job_name) {

 arg_tmp <- paste0(lapply(X = entry$function_args, FUN = function(X){
  str_form("--{{X}} {{py_format}}", X = X, py_format = sprintf("{%s}", X)) }),
  collapse = "  ")

 rendered_temp <- str_form(read_text("/jenkins/fab_task_template.txt"),
                           job_name = job_name,
                           project_dir = conf$project_name,
                           path_to_file = entry$file_location,
                           arg_tmp = arg_tmp,
                           arg_list = paste0(entry$function_args, collapse = ", "))
 write(rendered_temp, file = "fabfile.py", append = TRUE)

 message("Job Appended successfully...")

}


#' @title build_virtualenv_job
#' @description Builds jenkins xml file to deploy virtualenvironment.

build_virtualenv_job <- function(conf) {

 message("Reading virtualenvironment template...")
 virtualenv_template = str_form(read_text("/jenkins/create_env_jenkins.txt"),
                                project_dir = conf$project_name)

 generate_xml_config(job_type = "create_env", job_code = virtualenv_template,
                     project_url = conf$github_url, job_name = "create_env",
                     github_https_address = convert_git_url(conf$github_url))

 message("Virtualenv job created successfully...")
}


#' @title build_packrat_job
#' @description Builds packrat deployment job.

build_packrat_job <- function(conf) {

 message("Inserting packrat task...")
 packrat_task = mmkit:::read_text("/jenkins/packrat_task.txt")

 packrat_task <- str_form(packrat_task, project_dir = conf$project_name)
 write(packrat_task, file = "fabfile.py", append = TRUE)
 message("Packrat job successfully created...")

}


#' @title build_parallel_run_job
#' @description Builds jenkins job for parallel execution of task.

build_parallel_run_job <- function(conf, job_name, args, iter_arg = NULL) {

 message("Building parallel task execution job...")

 if (is.null(iter_arg)) {
  return(message("No iter arg specified... not defining parallel executor..."))
 }

 if (!iter_arg %in% args) {
  warning("iter arg not found in deploy.yaml args!")
 }

 args <- args[!args %in% iter_arg]

 if (length(args) > 0) {

  message("defining argument strings")
  arg_defs = paste0(lapply(args, FUN = function(X) {
   str_form('def {{X}} = params["{{X}}"]', X = X)
  }), collapse = "\n")

  arg_list = paste0(lapply(args, FUN = function(X) {
   str_form("{{X}}=${{X}}", X = X)
  }), collapse = "\n")

  arg_params <- paste0(lapply(args, FUN = function(X) {
   str_form(mmkit:::read_text("/jenkins/parallel_execute_params.txt"), arg = X)
  }), collapse = "\n")

 }else{

  arg_defs = ""
  arg_list = ""
  arg_params = ""

 }

 message("Generating job code...")
 job_code = str_form(read_text("/jenkins/jenkins-parallel-run-template.txt"),
                     job_name = job_name, iter_arg = iter_arg,
                     arg_defs = arg_defs, arg_list = arg_list)

 message("Generating xml template...")
 rendered <- str_form(mmkit:::read_text("/jenkins/jenkins_parallel_execute_template.xml"),
                      email = conf$user_email, job_code = job_code,
                      arg_params = arg_params)

 writeLines(rendered, sprintf("jenkins/parallel_execute_%s.xml", job_name))
 message("Parallel task execution job successfully created...")

}

